#!/usr/bin/env dash

if [ -z "${logger_trace+x}" ]; then
    COLOR_RESET="$(tput sgr0)"
    COLOR_RED="$(tput setaf 1)"
    COLOR_GREEN="$(tput setaf 2)"
    COLOR_YELLOW="$(tput setaf 3)"
    COLOR_BLUE="$(tput setaf 4)"
    COLOR_PURPLE="$(tput setaf 5)"
    COLOR_CYAN="$(tput setaf 6)"
    COLOR_GREY="$(tput setaf 7)"
    COLOR_LIGHTGREY="$(tput setaf 8)"
    . "./log4sh.${LOGGING_LEVEL:-all}"
fi