#!/usr/bin/env dash

case ${HOMEKIT_SH_LOGGING:-stderr} in
    log4sh)
        . ./log4sh
        ;;
    syslog)
        . ./logging.syslog
        ;;
    stderr)
        if [ -z "${logger_trace+x}" ]; then
            COLOR_RESET()     { tput sgr0; }
            COLOR_RED()       { tput setaf 1; }
            COLOR_GREEN()     { tput setaf 2; }
            COLOR_YELLOW()    { tput setaf 3; }
            COLOR_BLUE()      { tput setaf 4; }
            COLOR_PURPLE()    { tput setaf 5; }
            COLOR_CYAN()      { tput setaf 6; }
            COLOR_GREY()      { tput setaf 7; }
            COLOR_LIGHTGREY() { tput setaf 8; }
            logger_log()      { printf '%s %-5s %s%s\n' "$2$(date +%Y-%m-%d' '%H:%M:%S.%3N)" "$1" "[${REMOTE_ADDR:-}:${REMOTE_PORT:-}] $(basename "$0") - $3" "$(COLOR_RESET)" >&2; }

            . "./logging.$HOMEKIT_SH_LOGGING_LEVEL"
        fi
        ;;
    *)
        echo "Invalid value for HOMEKIT_SH_LOGGING: $HOMEKIT_SH_LOGGING. Logging disabled." >&2
esac
