#!/bin/sh

export PARALLEL_SHELL="dash"
#export LOGGING_LEVEL=warn

#export HOMEKIT_SH_CACHE_TOML=true
export HOMEKIT_SH_CACHE_TOML_DISK=true
export HOMEKIT_SH_CACHE_ACCESSORIES=true
export HOMEKIT_SH_CACHE_CHARACTERISTICS=true
export HOMEKIT_SH_CACHE_VALUES=15