#! /usr/bin/env dash
#! nix-shell --pure --keep LOGGING_LEVEL --keep PROFILING -i dash -I channel:nixos-23.05-small -p dash nix jq yq yajsv parallel findutils
. ./logging
. ./profiling
set -eu

logger_info 'Invoked: api/accessories'
logger_trace 'api/accessories'

. ./util/cache_set.sh

accessories=$(find ./accessories -name '*.toml' |\
              parallel --jobs 0${PROFILING:+1} "./util/tomlq-cached.sh -c '.services | group_by(.type) | .[]' {} | tr '\n' '\0' | xargs -0 -I[] ./util/generate_service.sh '[]' | jq -cs '{ aid: \$aid, services: map({type, iid, characteristics}) }' --argjson aid \$(./util/aid.sh {})" |\
              jq -cs '{accessories: .}')

./util/respond.sh 200 "$accessories"
